### ISSUE TITLE
App config does not work for building on soruce

### ISSUE THREAD

**Issue by PaulLockett** [livekit/agents-playground#43]
### What I expect
when the appConfig is set the the app will build without issue for the example config

### What happened 
I got This build error

```bash
...
Compiled successfully
   Collecting page data ...
   Generating static pages (0/3) ...
parsedConfig:  title: 'LiveKit Agent Playground' description: 'LiveKit Agent Playground allows you to test your LiveKit Agent integration by connecting to your LiveKit Cloud or self-hosted instance.' github_link: 'https://github.com/livekit/agents-playground' theme_color: 'cyan' video_fit: 'cover' # 'contain' or 'cover' outputs: audio: true # Enable or disable audio output video: true # Enable or disable video output chat: true  # Enable or disable chat feature inputs: mic: true    # Enable or disable microphone input camera: true # Enable or disable camera input sip: true    # Enable or disable SIP input 

 ✓ Generating static pages (3/3) 
TypeError: Cannot read properties of undefined (reading 'audio')
    at m (/vercel/path0/.next/server/pages/index.js:1:26966)
    at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'audio')
    at m (/vercel/path0/.next/server/pages/index.js:1:26966)
    at Wc (/vercel/path0/node_modules/react-dom/cjs/react-do
 ...
 ```

### Reproduction

1. Fork the repo.
2. attempt to deploy on Vercel with the proper environmental variables

### System Info

```shell
I deployed on Vercel by using a fresh fork of the repo
```

### Severity

serious, but I can work around it

### Additional Information

This makes the config unuseable.

**Comment by davidzhao** [comment]
can you share the appConfig you are using?
